language: node_js
node_js: 
  - 12
before_install:
  - npm install
  - export NODE_ENV=production
script:
  - npm test
before_script: npm install -g mocha
before_script: npm install -g chai
before_script: npm install -g chai-http
before_script: npm install -g should
before_script: npm install -g typescript-require